# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["paul.ionkin@gmail.com"]
description = "hCaptcha Serverless on Fastly Compute@Edge (Rust)"
language = "rust"
manifest_version = 2
name = "hcaptcha-fastly-compute"
service_id = ""

[local_server]
    [local_server.backends]
        [local_server.backends.Origin]
            url = "http://127.0.0.1:8081"
        [local_server.backends.hCaptcha]
            url = "https://hcaptcha.com"
    [local_server.dictionaries]
        [local_server.dictionaries.hcaptcha]
            file = "hcaptcha.json"
            format = "json"
